# Generated by Django 3.1 on 2020-09-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('releasedate', models.DateField()),
                ('hero', models.CharField(max_length=50)),
                ('heroine', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
