from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def welcome(request):
	request.session.set_test_cookie()
	data='<h1> Welcome to Study Online.</h1>'
	return HttpResponse(data)

def check_cookie(request):

	if request.session.test_cookie_worked():
		data='<h1>Cookie Object got generated by the server</h1>'

		print('Cookie Object got generated by the server ')

		#request.session.delete_test_cookie()
		
		return HttpResponse(data)